name: Build and Publish My GitBook

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    env:
      MY_SECRET   : ${{secrets.GH_ACCESS_TOKEN}}
      USER_NAME   : ${{secrets.GH_USERNAME}}
      USER_EMAIL  : ${{secrets.GH_EMAIL}}
      BOOK_DIR    : .

    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v4
    - name: Build and Deploy 🚀
      uses: LawrenceHwang/gitbook-build-publish-action@bugfix
